/**
 * `agrune maps types` — read the project lockfile and emit `.d.ts` with
 * host / per-host targetId union types.
 *
 * Default output: `node_modules/.agrune/maps.d.ts`. Consumers add
 * `/// <reference types="..." />` or let TypeScript resolve via
 * `node_modules/.agrune/maps.d.ts` automatically (Node 22 + TS 5 both
 * respect ambient `.d.ts` files discoverable through tsconfig `include`).
 *
 * v0.5 MVP: flat top-level type alias + a mapped namespace. Plan 03 future
 * work: extend with macro id / repeat id unions once seed manifests grow
 * beyond read-only targets.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import {
  readCacheEntry,
  readLockfile,
  type Lockfile,
  type RegistryEntry,
} from '../index.js'
import { errorExit, makeColor, parseArgs } from './shared.js'

export interface TypesCliDependencies {
  readCache?: typeof readCacheEntry
  readLock?: typeof readLockfile
  cwd?: () => string
  writeOut?: (path: string, content: string) => Promise<void>
}

const DEFAULT_OUT_REL = 'node_modules/.agrune/maps.d.ts'

/**
 * Run `agrune maps types`. Returns a process exit code — never throws.
 */
export async function runTypesCli(
  argv: string[],
  deps: TypesCliDependencies = {},
): Promise<number> {
  const color = makeColor()
  let parsed
  try {
    parsed = parseArgs(argv, { option: ['out', 'cwd'] })
  } catch (err) {
    return errorExit(err)
  }

  const readCache = deps.readCache ?? readCacheEntry
  const readLock = deps.readLock ?? readLockfile
  const cwd = (deps.cwd ?? process.cwd)()
  const projectCwd = parsed.options['cwd'] ?? cwd
  const outPath = parsed.options['out'] ?? join(projectCwd, DEFAULT_OUT_REL)

  let lock: Lockfile
  try {
    lock = await readLock(projectCwd)
  } catch (err) {
    return errorExit(err)
  }

  // Build the emitted `.d.ts` content from the lockfile + cached entries.
  const perHostTargets: Array<{ host: string; targetIds: string[] }> = []
  for (const entry of lock.entries) {
    let cached: RegistryEntry | null = null
    try {
      cached = await readCache(entry.host, entry.version)
    } catch (err) {
      // A missing / schema-invalid cache for one host should not take down
      // the entire emission — surface it as a warning and continue with an
      // empty targetId list for that host.
      process.stderr.write(
        color.yellow(`[agrune maps types] warning: cache miss for ${entry.host}@${entry.version}: ${(err as Error).message}\n`),
      )
      perHostTargets.push({ host: entry.host, targetIds: [] })
      continue
    }
    if (!cached) {
      perHostTargets.push({ host: entry.host, targetIds: [] })
      continue
    }
    const ids: string[] = []
    for (const group of cached.manifest.groups) {
      for (const t of group.targets) ids.push(t.targetId)
      for (const r of group.repeats ?? []) {
        for (const t of r.targets) ids.push(`${r.repeatId}:${t.targetId}`)
      }
    }
    perHostTargets.push({ host: entry.host, targetIds: Array.from(new Set(ids)).sort() })
  }

  const dts = renderDts(perHostTargets)

  const writeOut = deps.writeOut ?? (async (p, content) => {
    await mkdir(dirname(p), { recursive: true })
    await writeFile(p, content, 'utf8')
  })

  try {
    await writeOut(outPath, dts)
  } catch (err) {
    return errorExit(err)
  }

  process.stdout.write(
    color.green('✓') +
      ` Wrote ${perHostTargets.length} host type declaration${perHostTargets.length === 1 ? '' : 's'} to ${outPath}\n`,
  )
  return 0
}

/**
 * Emit the `.d.ts` payload. When the lockfile is empty, host union collapses
 * to `never` — typed consumers still compile, but any concrete host literal
 * will (correctly) fail assignability.
 */
function renderDts(perHostTargets: Array<{ host: string; targetIds: string[] }>): string {
  const hosts = perHostTargets.map((p) => p.host).sort()
  const hostUnion = hosts.length === 0 ? 'never' : hosts.map((h) => `'${h}'`).join(' | ')

  const blocks: string[] = []
  blocks.push('// Generated by `agrune maps types` — do not edit by hand.')
  blocks.push('// Regenerate after `agrune maps add/remove` by re-running the command.')
  blocks.push('')
  blocks.push(`export type AgruneMapsHost = ${hostUnion}`)
  blocks.push('')
  blocks.push('export interface AgruneMapsTargetIds {')
  if (perHostTargets.length === 0) {
    blocks.push('  // (lockfile empty — populate via `agrune maps add <host>`)')
  } else {
    for (const { host, targetIds } of perHostTargets) {
      const union = targetIds.length === 0 ? 'never' : targetIds.map((t) => `'${t}'`).join(' | ')
      blocks.push(`  '${host}': ${union}`)
    }
  }
  blocks.push('}')
  blocks.push('')
  return blocks.join('\n')
}
