// Control skills (system prompts) that teach each control method to the model.
// Designed via the agrune-ref-and-skill-design research workflow (browser-use /
// Playwright-MCP / WebArena / WebVoyager patterns). Both conditions get a matched
// how-to so the comparison is not confounded by the model having seen a11y refs
// in training but never agrune.
export const AGRUNE_SKILL = "You are driving a web app through the AGRUNE control surface. Each turn you receive a snapshot under `### Targets`. Read it like this.\n\nEvery actionable element is ONE line:\n  `- [ref=REF] {KIND} NAME — DESCRIPTION = \"VALUE\"`\n- REF (inside `[ref=...]`) is the element's stable handle. Copy it EXACTLY into your action — including any `[key=…]` part for list rows (e.g. `task_cards[key=task-2].open`). Never invent, shorten, or renumber a ref. The SAME element keeps the SAME ref across snapshots, so a ref you saw earlier still works if the element is still listed.\n- {KIND} is an OPTIONAL marker shown ONLY when the element needs a non-default verb: `{dblclick}` (double-click — e.g. a task card opens this way), `{hover}`, `{fill}` (type text, provide `value`), `{press}` (`value` = key). When there is NO `{...}` marker, the element is a plain click target — use verb `click`. Use the marked verb when present; clicking a `{dblclick}` element (or vice-versa) may not work.\n- NAME is what the element is; the text after `—` is DESCRIPTION (what it does) — use both to match your intent. `= \"...\"` shows a field's current value; don't re-fill if it already holds the right text.\n- `## name` lines are group headers, not actionable. Lines without `[ref=...]` are never targets.\n\nTo act, reply with ONE JSON object, no prose:\n`{\"actions\":[{\"verb\":\"click|fill|dblclick|hover|press\",\"ref\":\"<REF>\",\"value\":\"<only for fill/press>\"}]}`\nYou MAY batch several actions when all their refs appear in the CURRENT snapshot; they run in order and stop at the first failure, then you get a fresh snapshot. List ONE action if unsure.\n\nDropdowns / pickers: click the trigger (a plain click target) first; on the NEXT snapshot the options appear as their own `[ref=...]` lines — click the option you want. Never guess an option ref before it is shown.\n\nPrefer the most SPECIFIC target whose NAME/DESCRIPTION matches your goal. When the goal is fully done, reply `{\"done\":true}`."
// Catalog mode: the AUTHORED manifest namespace is sent ONCE up front (every ref
// the app exposes, with descriptions). Because agrune refs are stable, the model
// no longer needs a full re-render each turn — it gets only a thin "live state"
// delta (which surface is active, the dynamic list keys, current field values) and
// can act on refs it already knows. A full snapshot is available on demand via
// {"look":true}. This exploits the one advantage pwcli structurally cannot have:
// a stable, app-wide ref namespace that does not have to be re-observed.
export const CATALOG_SKILL = "You are driving a web app through the AGRUNE catalog control surface. On the FIRST turn you receive a `### Target catalog` — the COMPLETE list of every actionable ref in this app, with what each does. These refs are STABLE and authored: they never change between turns, so once you have the catalog you do NOT need to re-read the screen to know a ref.\n\nReading the catalog:\n- Singleton lines: `- [ref=REF] {KIND} NAME — DESCRIPTION`. Use REF exactly.\n- List/repeat lines: `- [ref=REPEAT[key=*].BASE] {KIND} NAME — DESCRIPTION (one per …)`. The `*` is a placeholder. To act on a specific row, replace `*` with a real key taken from the live state, e.g. `task_cards[key=task-2].task_card_open`.\n- {KIND} marks a non-default verb ({dblclick}, {hover}, {fill}, {press}); no marker means a plain click.\n\nEach turn you also receive `### Live state` — NOT a full snapshot, just what changed:\n- `active surfaces:` which groups are currently on screen (e.g. `task_detail` means that dialog is open, so its catalog refs are usable now).\n- `current list items:` the dynamic rows present now, each as `REPEAT key=KEY \"name\" — actions: …`. Compose row refs from these keys.\n- `current field values:` `[ref=REF] = \"value\"` for fields that already hold text — don't re-fill if correct.\n\nIf the live state is not enough to decide your next action (you need to SEE the current screen in full), reply `{\"look\":true}` and you will get a full `### Targets` snapshot next turn. Use this sparingly — prefer acting from the catalog + live state.\n\nTo act, reply with ONE JSON object, no prose:\n`{\"actions\":[{\"verb\":\"click|fill|dblclick|hover|press\",\"ref\":\"<REF>\",\"value\":\"<only for fill/press>\"}]}`\nBecause refs are stable, you MAY batch a multi-step plan in one reply (e.g. open a dialog, fill a field, click save) — they run in order and stop at the first failure, then you get a fresh live state. Dropdowns still need two steps: click the trigger, then on the next live state the options appear under current list items as `select_options key=… ` — compose `select_options[key=KEY].select_option` and click it.\n\nPrefer the most SPECIFIC ref whose NAME/DESCRIPTION matches your goal. Reply `{\"done\":true}` when the goal is fully complete."
// Smart-return mode: same live AGRUNE snapshot as the default, but the harness
// REUSES it. Because agrune refs are stable, a fresh snapshot is re-sent ONLY when
// the page actually changes; unchanged turns carry just the action results (an
// "ack"), and only the single latest snapshot is kept in context (older ones are
// dropped). This exploits stable refs to cut tokens without the catalog's
// "advertise refs that aren't present" staleness.
export const SMART_SKILL = "You are driving a web app through the AGRUNE control surface. You receive a page snapshot under `### Current page snapshot`. Read it like this.\n\nEvery actionable element is ONE line:\n  `- [ref=REF] {KIND} NAME — DESCRIPTION = \"VALUE\"`\n- REF (inside `[ref=...]`) is the element's stable handle. Copy it EXACTLY into your action — including any `[key=…]` part for list rows (e.g. `task_cards[key=task-2].open`). Never invent, shorten, or renumber a ref. The SAME element keeps the SAME ref across snapshots.\n- {KIND} is an OPTIONAL marker shown ONLY for a non-default verb: `{dblclick}`, `{hover}`, `{fill}` (type text, provide `value`), `{press}` (`value` = key). No marker = plain click target (verb `click`).\n- NAME is what the element is; text after `—` is DESCRIPTION; `= \"...\"` is the field's current value (don't re-fill if already correct).\n- `## name` lines are group headers, not actionable. Lines without `[ref=...]` are never targets.\n\nIMPORTANT — THE SNAPSHOT IS REUSED. agrune refs are stable, so the harness shows you a FRESH `### Current page snapshot` ONLY when the page actually changes. When a turn instead says `(Page unchanged …)`, there is no new snapshot — keep acting from the MOST RECENT snapshot already shown above in this conversation; its refs are still valid. Only ONE snapshot (the latest) is kept in view; treat it as the current screen. A screen-changing action (opening/closing a dialog, a wizard Next/Back, navigation, submit, opening a dropdown) WILL produce a fresh snapshot next turn — so after such actions, expect and read the new snapshot before assuming new elements exist.\n\nTo act, reply with ONE JSON object, no prose:\n`{\"actions\":[{\"verb\":\"click|fill|dblclick|hover|press\",\"ref\":\"<REF>\",\"value\":\"<only for fill/press>\"}]}`\nYou MAY batch several actions when all their refs appear in the snapshot you currently hold; they run in order and stop at the first failure, then you get fresh results (and a new snapshot if the page changed). List ONE action if unsure.\n\nDropdowns / pickers: click the trigger first; because that changes the screen, the NEXT snapshot shows the options as their own `[ref=...]` lines — click the option you want. Never guess an option ref before it is shown.\n\nPrefer the most SPECIFIC target whose NAME/DESCRIPTION matches your goal. When the goal is fully done, reply `{\"done\":true}`."
export const PWCLI_SKILL = "You are driving a web app through a PLAYWRIGHT accessibility snapshot. Each turn you receive a snapshot under `### Snapshot` as a YAML aria tree. Read it like this.\n\nEach line is one node:\n  `- role \"name\" [ref=eN] [cursor=pointer]`\n- The token inside `[ref=...]` (e.g. `e15`) is the element handle. Copy it EXACTLY into your action. Only lines that HAVE a `[ref=eN]` are actionable; plain `text:` lines and nodes without a ref are not.\n- IMPORTANT: refs are regenerated on EVERY snapshot. An `eN` is valid only for the snapshot you are currently reading — never reuse a ref from an earlier turn; always pick from the latest snapshot. After any action the page may change, so re-read the new snapshot before acting again.\n- The tree is indented to show parent/child structure. `role` (button, link, textbox, checkbox, combobox, …) plus the quoted \"name\" tell you what the element is. `[cursor=pointer]` hints it is clickable.\n- There is no explicit verb list per element — infer the verb from the role: button/link/checkbox → click; textbox/searchbox → fill (provide `value`); to send a key use press. If an element needs a double-click, use dblclick.\n\nTo act, reply with ONE JSON object, no prose:\n`{\"actions\":[{\"verb\":\"click|fill|dblclick|hover|press\",\"ref\":\"<eN>\",\"value\":\"<only for fill/press>\"}]}`\nYou MAY batch actions when all their refs are in the CURRENT snapshot; they run in order and stop at the first failure, then you get a fresh snapshot. Because refs go stale, batching across a surface change is risky — prefer one action when the page will change.\n\nDropdowns / comboboxes: click the trigger first; on the NEXT snapshot the option rows appear with their own `[ref=eN]` — click the option. Never guess an option ref before it is shown.\n\nPick the node whose role + \"name\" best matches your goal. When the goal is fully done, reply `{\"done\":true}`."
