import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { HOST_NAME } from '../constants.js'
import { getNativeHostManifestPath, MCP_SERVER_ENTRY, NATIVE_HOST_WRAPPER } from './paths.js'

export function getNativeHostManifest(binaryPath: string, extensionIds: string[]) {
  return {
    name: HOST_NAME,
    description: 'agrune MCP server native messaging host',
    path: binaryPath,
    type: 'stdio' as const,
    allowed_origins: extensionIds.map(id => `chrome-extension://${id}/`),
  }
}

export function deriveExtensionIdFromManifestKey(key: string): string {
  const publicKeyBytes = Buffer.from(key, 'base64')
  if (publicKeyBytes.length === 0) {
    throw new Error('Extension manifest key is empty or invalid')
  }
  const hash = createHash('sha256').update(publicKeyBytes).digest()
  let extensionId = ''
  for (const byte of hash.subarray(0, 16)) {
    extensionId += String.fromCharCode('a'.charCodeAt(0) + (byte >> 4))
    extensionId += String.fromCharCode('a'.charCodeAt(0) + (byte & 0x0f))
  }
  return extensionId
}

export function getNativeHostWrapper(nodePath = process.execPath): string {
  return [
    '#!/bin/sh',
    '# agrune native messaging host',
    '# Generated by @agrune/cli - do not edit manually',
    `exec "${nodePath}" "${MCP_SERVER_ENTRY}" --native-host`,
    '',
  ].join('\n')
}

export function installNativeHostWrapper(): string {
  const wrapper = getNativeHostWrapper()
  mkdirSync(dirname(NATIVE_HOST_WRAPPER), { recursive: true })
  writeFileSync(NATIVE_HOST_WRAPPER, wrapper, { mode: 0o755 })
  return NATIVE_HOST_WRAPPER
}

export function installNativeHostManifest(extensionIds: string[]): string {
  const manifestPath = getNativeHostManifestPath()
  const manifest = getNativeHostManifest(NATIVE_HOST_WRAPPER, extensionIds)
  mkdirSync(dirname(manifestPath), { recursive: true })
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8')
  return manifestPath
}
