// ─── INLINE SCHEMA COPY — v0.5 MVP ──────────────────────────────────────────
//
// DO NOT EDIT this file without syncing from the source-of-truth in the main
// agrune monorepo:
//   - packages/manifest/src/schema.ts   (ManifestSchema + ActionKind + Group/Target/...)
//   - packages/registry/src/schema.ts   (RegistryMetadataSchema + RegistryEntrySchema
//                                        + tier × allowedEnvironments superRefine)
//   - packages/registry/src/content-hash.ts  (sha256 + fast-json-stable-stringify)
//
// SYNC CHECKPOINT: when any of the files above change in the main repo, the
// inline copy below MUST be updated in the same PR.
//
// REMOVAL PATH (v0.6+):
// Once `@agrune/registry` is published to npm, replace this file with:
//
//   export { RegistryEntrySchema, contentHash } from '@agrune/registry'
//
// and drop the three inline definitions below. See
// `.planning/phases/18-registry/external-sync-instructions.md` § 7.
// ───────────────────────────────────────────────────────────────────────────

import { z } from 'zod'
import { createHash } from 'node:crypto'
import stableStringify from 'fast-json-stable-stringify'

// ─── @agrune/manifest ManifestSchema (v3) ──────────────────────────────────

const ActionKindSchema = z.enum([
  'click', 'fill', 'dblclick', 'contextmenu', 'hover', 'longpress',
])

const SelectorLadderSchema = z
  .object({
    role: z.object({ name: z.string(), level: z.string().optional() }).optional(),
    text: z.string().optional(),
    testId: z.string().optional(),
    attr: z.string().optional(),
    css: z.string().optional(),
    fiber: z
      .object({
        path: z
          .array(
            z.object({
              componentName: z.string(),
              key: z.string().nullable(),
              index: z.number().int().nonnegative(),
            }),
          )
          .min(1)
          .max(8),
      })
      .optional(),
  })
  .refine(
    (v) => Boolean(v.role || v.text || v.testId || v.attr || v.css || v.fiber),
    { message: 'SelectorLadder must define at least one of: role, text, testId, attr, css, fiber' },
  )

const TargetSchema = z.object({
  targetId: z.string().min(1),
  name: z.string().optional(),
  desc: z.string().optional(),
  actionKinds: z.array(ActionKindSchema).min(1),
  selector: SelectorLadderSchema,
  // sensitive OR-only lock — false 는 schema 차단 (Pitfall 5)
  sensitive: z.literal(true).optional(),
})

const RepeatSchema = z.object({
  repeatId: z.string().min(1),
  template: z.string(),
  keyFrom: z.string(),
  nameFrom: z.string().optional(),
  strategy: z.enum(['dom', 'virtualized']),
  containerSelector: SelectorLadderSchema.optional(),
  targets: z.array(TargetSchema),
})

const MacroStepSchema = z.object({
  targetId: z.string().min(1),
  action: ActionKindSchema,
  value: z.string().optional(),
  sensitive: z.literal(true).optional(),
})

const MacroSchema = z.object({
  macroId: z.string().min(1),
  name: z.string().optional(),
  desc: z.string().optional(),
  params: z.record(
    z.string(),
    z.object({
      type: z.enum(['string', 'number', 'boolean']),
      required: z.boolean().optional(),
    }),
  ),
  steps: z.array(MacroStepSchema).min(1),
  precondition: z.string().optional(),
  postcondition: z.string().optional(),
  circuitBreaker: z
    .object({
      maxRetries: z.number().int().nonnegative(),
      resetAfterMs: z.number().int().nonnegative().optional(),
    })
    .optional(),
})

const GroupSchema = z.object({
  groupId: z.string().min(1),
  name: z.string().optional(),
  desc: z.string().optional(),
  route: z.string().optional(),
  targets: z.array(TargetSchema),
  repeats: z.array(RepeatSchema).optional(),
})

export const ManifestSchema = z.object({
  version: z.literal(3),
  groups: z.array(GroupSchema),
  macros: z.array(MacroSchema).optional(),
})

// ─── @agrune/registry RegistryEntrySchema (wraps manifest) ─────────────────

export const RegistryTierSchema = z.enum(['verified', 'community', 'unlisted'])

export const AllowedEnvironmentsSchema = z
  .array(z.enum(['dev', 'prod']))
  .default(['dev'])

export const RegistryMetadataSchema = z.strictObject({
  host: z.string().min(1),
  version: z.string().min(1),
  tier: RegistryTierSchema,
  author: z.string().min(1),
  submittedAt: z.string().datetime(),
  reviewedBy: z.array(z.string()).optional(),
  allowedEnvironments: AllowedEnvironmentsSchema,
  seedUrl: z.string().url().optional(),
  staleSince: z.string().datetime().optional(),
})

/**
 * RegistryEntrySchema — strict wrapper around ManifestSchema with tier × env
 * cross-field refinement (Pitfall 7: community tier cannot request prod).
 */
export const RegistryEntrySchema = z
  .strictObject({
    registry: RegistryMetadataSchema,
    manifest: ManifestSchema,
  })
  .superRefine((entry, ctx) => {
    const { tier, allowedEnvironments } = entry.registry
    if (tier !== 'verified' && allowedEnvironments.includes('prod')) {
      ctx.addIssue({
        code: 'custom',
        message: `tier='${tier}' cannot enable 'prod' in allowedEnvironments (verified tier only)`,
        path: ['registry', 'allowedEnvironments'],
      })
    }
  })

// ─── contentHash (sha256 + canonical JSON) ──────────────────────────────────

/**
 * Deterministic sha256:<hex> of a manifest using fast-json-stable-stringify.
 * Must match packages/registry/src/content-hash.ts byte-for-byte.
 */
export function contentHash(manifest) {
  const canonical = stableStringify(manifest)
  const hex = createHash('sha256').update(canonical, 'utf-8').digest('hex')
  return `sha256:${hex}`
}
