// Verbatim help text. Reproduced byte-for-byte from SPEC Appendix A.5.
// The returned array is joined with '\n'; the final element is '' so the output ends with a
// newline after `agrune read`.

const HELP_LINES: string[] = [
  'agrune CLI',
  '',
  'Usage:',
  '  agrune daemon start [--headless] [--port 47654]   # foreground; default binds the workspace socket',
  '  agrune daemon stop',
  '  agrune daemon status',
  '  agrune daemon events [--json]',
  '',
  '  Browser commands auto-spawn a per-workspace daemon (detached) on first use.',
  '  Endpoint: ~/.agrune/run/<workspace-hash>/daemon.sock — override with',
  '  --host/--port (TCP) or AGRUNE_DAEMON_SOCKET.',
  '  agrune open <url>',
  '  agrune navigate <url>',
  '  agrune back | forward | reload',
  '  agrune resize <width> <height>',
  '  agrune evaluate <js> [--target <target-ref>] [--arg json] [--filename path]',
  '  agrune run-code-unsafe <js>|--code <js>|--file <path>',
  '  agrune console [--level debug|info|warning|error] [--all] [--filename path] [--json]',
  '  agrune network [--filter regexp] [--static] [--all] [--filename path] [--json]',
  '  agrune network request <index> [--part request-headers|request-body|response-headers|response-body] [--filename path]',
  '  agrune dialogs [--json]',
  '  agrune handle-dialog --accept|--dismiss [--prompt-text text]',
  '  agrune dialog accept|dismiss [--prompt-text text]',
  '  agrune file-choosers [--json]',
  '  agrune file-upload [path...]   # no paths cancels the pending chooser',
  '  agrune tabs',
  '  agrune tabs list',
  '  agrune tabs new <url>',
  '  agrune tabs focus <tabId>|--index <index>',
  '  agrune tabs select <tabId>|--index <index>',
  '  agrune tabs close [tabId|--index <index>]',
  '  agrune close [tabId|--index <index>]',
  '  agrune events [--json]',
  '  agrune targets [--mode outline|full] [--full] [--group <groupId>] [--group-ids csv] [--target <target-ref>] [--text] [--filename path] [--json]',
  '  agrune snapshot [--target <target-ref>] [--depth n] [--mode ai|default] [--boxes] [--include-text-content] [--filename path] [--json]',
  '  agrune click <target-ref> [--button left|right|middle] [--double-click] [--modifiers Alt,Shift]',
  '  agrune fill <target-ref> <value> [--strategy insert|keystroke|auto]',
  '  agrune fill-form --fields json|--file path',
  '  agrune type <target-ref> <text> [--submit] [--delay ms]',
  '  agrune press [target-ref] <key> [--target <target-ref>]',
  '  agrune select <target-ref> <value...> [--label|--index]',
  '  agrune upload <target-ref> <path...>',
  '  agrune drop <target-ref> [path...] [--data json|--text value|--uri value]',
  '  agrune drag <start-ref> --to <end-ref>',
  '  agrune wait <target-ref> [--state visible|hidden|enabled|disabled]',
  '  agrune wait --text <text> | --text-gone <text> | --time <seconds>',
  '  agrune screenshot [--output path] [--full-page] [--target <target-ref>] [--type png|jpeg]',
  '  agrune read',
  '',
]

export function helpText(): string {
  return HELP_LINES.join('\n')
}
